### ISSUE TITLE
List command: Type filter does not apply at all if passed type is unknown

### ISSUE THREAD

**Issue by adi64** [pointcloudtechnology/piccologs#3]
https://github.com/pointcloudtechnology/piccologs/blob/158be607c5d6ac2c0c9ea40ec74d37f20d035fb8/src/commands/list.js#L63

I can pass a type / category or a list of categories with the `--type` argument, e.g. `picco ls --type=migration`. However, if I pass a type that is unknown, it is discarded, and all entries are shown. I'd argue that if I pass a type that doesn't match anything, the result should be an empty set instead of all entries. Since there is a fixed list of supported types, I suggest throwing an error (or at least printing a warning) when passing a type that is unsupported.

**Comment by Floriszenz** [comment]
In my opinion, it isn't a nice user experience to show nothing but an error when passing an unknown type.
Rather than "punishing" the user for passing an invalid type by giving no valuable information (= the filtered changelog), its nicer to give the next best valuable information (= changelog with valid filter types applied).

A proposal for such behavior can be found at #4

**Comment by adi64** [comment]
I understand your point. I agree that it's not a particularly nice user experience to just "lecture" the user and not show any changelog information.

On the other hand, I am a considerable part of the (intended?) audience and I don't like tools that ignore my orders and do something else while trying to be helpful. I appreciate the effort, sure, but I don't have a problem with the "bad" user experience of just throwing an error. The user (i.e., I) used the tool wrong. Also it's not like the tool runs for multiple minutes or hours and then throws an error while discarding any work. I can immediately fix the command line and re-run the tool.
In a similar vein, I don't like how "plain" PHP, in its default configuration and without type annotations, tends to bend over backwards trying to keep running, even if the passed data doesn't make any sense at all or even if variables are undefined.

Also, I spend a good amount of time on the CLI and automating things, piping the output of one command to another. In that scenario, it's important that commands either do the right thing, or fail, in order to not run into trouble. For example, I have a script that filters existing backups for certain criteria that make them eligible for deletion, and then I delete those automatically. Imagine if the backup tool gets updated, one of the filters doesn't exist anymore, and it just prints a warning and continues to list *all* backup snapshots! (Yes, that is a more dramatic scenario, but you get the gist :D)

But it's not like I *demand* you to change the behavior. :D I can definitely live with the fix that PR #4 proposes. I just wanted to outline my motivation and reasoning.
